package shell

// Bash is the bash shell integration.
var PowerShell = Shell(`# Put the line below in ~\Documents\WindowsPowerShell\profile.ps1:
#
#   jump.exe shell powershell | Out-String | Invoke-Expression
#
# The following lines are autogenerated:

# TODO: provide PowerShell command
#
# __jump_prompt_command() {
#   local status=$?
#   jump chdir && return $status
# }

# TODO: provide PowerShell command
#
# __jump_hint() {
#   local term="${COMP_LINE/#{{.Bind}} /}"
#   jump hint $term
# }

# Performs the jump to the specified search $Terms.
#
function {{.Bind}} {
  [CmdletBinding()]
  param (
    [Parameter(
      Mandatory=$False,
      ValueFromPipeline=$True,
      ValueFromPipelineByPropertyName=$True,
      ValueFromRemainingArguments=$true
    )]
    [String[]]
    $Terms
  )
  $dir = jump.exe cd $Terms
  if (Test-Path $dir -PathType Container) {
    Set-Location $dir
  }
}

# TODO: provide PowerShell command
#
# [[ "$PROMPT_COMMAND" =~ __jump_prompt_command ]] || {
#   PROMPT_COMMAND="__jump_prompt_command;$PROMPT_COMMAND"
# }

# TODO: provide PowerShell command
#
# complete -o dirnames -C '__jump_hint' {{.Bind}}
`)
